name: test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.7
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: go test -v
